// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Students API"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Sinal de vida da aplicação.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observabilidade"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "{\\\"status\\\":\\\"ok\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Expõe contadores e histogramas por rota/método/status no formato\nde texto do Prometheus.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "observabilidade"
                ],
                "summary": "Métricas Prometheus",
                "responses": {
                    "200": {
                        "description": "Métricas no formato Prometheus",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/students": {
            "get": {
                "description": "Retorna uma página de estudantes com metadados de paginação\n(total, limit, offset). Aceita filtro opcional por ` + "`" + `active` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Lista estudantes (paginada)",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Filtra por ativo (true) ou inativo (false)",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Itens por página (1–100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Itens a pular",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.listStudentsResponse"
                        }
                    },
                    "400": {
                        "description": "parâmetro inválido",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um estudante. O CPF deve ter 11 dígitos (só números), ser\nválido pelos dígitos verificadores e único; o e-mail deve ter\nformato válido. ` + "`" + `active` + "`" + ` é obrigatório.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Cria um estudante",
                "parameters": [
                    {
                        "description": "Dados do estudante",
                        "name": "student",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.StudentResponse"
                        }
                    },
                    "400": {
                        "description": "corpo/validação inválidos",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "409": {
                        "description": "CPF já cadastrado",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        },
        "/students/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Busca um estudante por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do estudante",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StudentResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "não encontrado",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Atualização parcial: apenas os campos enviados são alterados.\nAs mesmas regras de validação de CPF e e-mail se aplicam.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Atualiza um estudante (parcial)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do estudante",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos a atualizar",
                        "name": "student",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StudentResponse"
                        }
                    },
                    "400": {
                        "description": "corpo/validação inválidos",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "não encontrado",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "409": {
                        "description": "CPF já cadastrado",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "students"
                ],
                "summary": "Remove um estudante",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do estudante",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "sem conteúdo"
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    },
                    "404": {
                        "description": "não encontrado",
                        "schema": {
                            "$ref": "#/definitions/api.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateStudentRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "ponteiro para diferenciar \"false\" de \"campo ausente\"",
                    "type": "boolean"
                },
                "age": {
                    "type": "integer"
                },
                "cpf": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.StudentResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer"
                },
                "cpf": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "api.UpdateStudentRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "age": {
                    "type": "integer"
                },
                "cpf": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.listStudentsResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StudentResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Students API",
	Description:      "API RESTful para gerenciar estudantes (CRUD), com validação de\nCPF (dígitos verificadores + unicidade) e e-mail, listagem\npaginada, cache e observabilidade.\n\nErros são retornados como JSON no formato `{\"error\": \"mensagem\"}`\ncom o status HTTP adequado (400 inválido, 404 não encontrado,\n409 CPF duplicado).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
